name: 'rufford'
description: 'Location based hunt for Rufford Country park'
#publish_to: 'none'


version: 0.2.8+28


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mark922_flutter_lottie: ^0.2.5
  residemenu: 1.2.5
  ar_flutter_plugin: ^0.6.1
  share:
  url_launcher:
  carousel_pro:
#  google_maps_flutter: ^2.0.3
  tflite: ^1.0.5
  percent_indicator: ^2.1.1+1
  camera: ^0.5.7+4
#  cloud_firestore: ^0.14.1+3
#  firebase_core: ^0.5.0+1
#  in_app_purchase: ^0.6.0
  maps_launcher: ^2.0.0
  shared_preferences: ^2.0.5
  liquid_progress_indicator: ^0.3.2
  rflutter_alert: ^1.1.0
  beacons_plugin: ^2.0.8
  sensors: ^2.0.0
  simple_animations: ^2.4.2
  pedometer: ^3.0.0
  intro_slider: ^2.4.1
  nfc_in_flutter: ^2.0.4
  intl: ^0.17.0
  nfc_manager: ^3.0.0+2
  photo_view: ^0.13.0
  flutter_map: ^0.13.0
#  camera_deep_ar: ^0.0.1
  latlong: ^0.6.1
#  user_location: ^0.1.3
#  latlng: ^0.1.0
  flutter_web_browser: ^0.15.0
  permission_handler: ^8.1.4+2
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
  geoflutterfire: ^3.0.1





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS stylar_flutter_plugine icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

#  beacons_plugin:
#    path: ../


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/background.jpg
    - assets/images/card1.jpg
    - assets/images/card2.jpg
    - assets/images/card3.jpg
    - assets/images/card4.jpeg
    - assets/images/map.jpg
    - assets/images/camera.jpg
    - assets/local.json
    - assets/confetti.json
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/images/confetti.gif
    - assets/images/walking.png
    - assets/images/game.png
    - assets/images/quiz.png
    - assets/images/prize.png
    - assets/images/tag.png
    - assets/icon/logo.jpg
    - assets/icon/white.png
    - assets/icon/logo2.png
    - assets/icon/logo3.png
    - assets/images/NFCblack.png
    - assets/
    - assets/images/




  fonts:
    - family: Acme
      fonts:
        - asset:  assets/font/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf
          weight: 200



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  background_image: "assets/icon/splash.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.jpg"
  adaptive_icon_background: "assets/icon/white.png"
  adaptive_icon_foreground: "assets/icon/logo2.png"